jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://203.195.210.16:3306/datashop?useUnicode=true
  userName: root
  password: 123456


server:
  port: 8091
  context-path: /dataapi

#filePath
file:
  base-path: /app/nginx/html
  static-path: /public

edite:
  timeout: 300

