jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://dcds-m.dbsit.sfdc.com.cn:3306/dcds?useUnicode=true
  userName: dcds
  password: 6X2zyd1q4u


server:
  port: 8091
  context-path: /dataapi

#filePath
file:
  base-path: /app/nginx/html
  static-path: /public

edite:
  timeout: 300

