
#mybatis
mybatis:
  config_file: mybatis-config.xml
  mapper_path: /mapper/**.xml
  entity_package: com.datashop.domain

spring:
  jpa:
    show-sql: true
  profiles:
    active: dev
  session:
    store-type: none


#security
security:
  basic:
    enabled: false

java:
  home: E:\jdk\jdk1.8.0_65

server:
  session:
    cookie:
      max-age: 60
      http-only: true