
#mybatis
mybatis:
  config_file: mybatis-config.xml
  mapper_path: /mapper/**.xml
  entity_package: com.datashop.domain

spring:
  jpa:
    show-sql: true
  profiles:
    active: dev

#security
security:
  basic:
    enabled: false